name: Next.js CI Pipeline

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run lint (optional, remove if you don’t use ESLint)
      - name: Run lint
        run: npm run lint --if-present

      # Build Next.js project (this ensures the code is valid)
      - name: Build project
        run: npm run build
